steps:
  - key: one
    label: Step 1
    command: 'false'
  - wait: 
    continue_on_failure: true
  - label: Check if step 1 was failed
    command: |
      if [ $(buildkite-agent step get "outcome" --step "one") == "hard_failed" ]; then
        buildkite-agent meta-data set "step-one-result" "fail"
      fi
  - label: 'Step 1 result was:'
    command: buildkite-agent meta-data get "step-one-result"
  - if: false
    block: This is blocked
    label: Step 3
