steps:
  - label: 'Step 1'
    command: "false"
    key: 'one'

  - wait:
    continue_on_failure: true

  - block: "Block step here"
    if: ${buildkite-agent step get "outcome" --step "one"} == "hard_failed"
  - label: 'Step 3'
    command: 'echo `buildkite-agent step get "outcome" --step "one"`'
