steps:
  - command: echo "Before trigger"
  - wait
  - command: echo "${build.env("BUILDKITE_COMMAND_EXIT_STATUS")}"
    label: "env test"
  - block: "previous result was: ${BUILDKITE_COMMAND_EXIT_STATUS}"
  - command: echo "END"
