steps:
  - command: buildkite-agent artifact upload test-files/step1/test.txt
    label: ":rocket: step 1"

  - command: buildkite-agent artifact upload test-files/step2/test.txt
    label: ":rocket: step 2"

  - command: buildkite-agent artifact upload test-files/step3/test.txt
    label: ":rocket: step 3"

  - command: buildkite-agent artifact download "test-files/*/*.txt"
    label: "download all"
