steps:
  - block: ":rocket: Release!"
    fields: 
      - text: "Name"
        hint: ":name_badge: The code name for this release"
        key: "release-name"
      - select: "Stream"
        hint: ":fork: Which release stream does this belong in?"
        key: "release-stream"
        default: "beta"
        options:
          - label: "Beta"
            value: "beta"
          - label: "Stable"
            value: "stable"
  - command: release.sh
    label: ":rocket:"
