steps:
  - command: echo 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"
      
  - wait:

  - block: ":warning: Build a release?"

  - command: echo 'hello'
    label: "I am unblocked"
