steps:
  - command: echo 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"
      
  - wait: 
    continue_on_failure: true
    
  - command: echo "Hieeeeee"

  - block: ":warning: Build a release?"

  - command: echo 'hello'
    label: "I am unblocked"
