steps:
  - command: echo 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"

  - wait: "wait 1"
    continue_on_failure: true
  
  - wait: "wait 2"
    continue_on_failure: true
    
  - command: echo "Hello, release me"

  - command: echo 'hello'
    label: "I am unblocked"
    agents:
      queue: "nithya"
