steps:
  - command: echo 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"
      
  - block: "this is block step"

  - wait: "wait 1"
    continue_on_failure: true
    
  - command: echo "Hello, release me"

  - command: echo 'hello'
    label: "I am unblocked"
    agents:
      queue: "nithya"
