steps:
  - command: buildkite-agent artifact upload artifacts_test01.txt && buildkite-agent artifact download artifacts_test01.txt .
    label: ":rocket: step 1"
    key: "This-is-a-key-from-the-first-step"
