steps:
  - command: echo 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"
      
  - wait: ~
    continue_on_failure: true
    
  - block: "Hello, release me"

  - command: echo 'hello'
    label: "I am unblocked"
