steps:
  - command: echo 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"
  
  - wait: ~
  
  - command: echo "first command"
  
  - wait: ~
      
  - block: "this is block step"
  
  - command: echo "second command"

  - wait: ~
    continue_on_failure: true
    
  - wait: ~
    continue_on_failure: true
    
  - command: echo "Hello, release me"

  - command: echo 'hello'
    label: "I am unblocked"
    agents:
      queue: "nithya"
