steps:
  - command: ech 'Hello Buildkite'
    label: ":rocket: step 1"
    agents:
      queue: "nithya"
    soft_fail:
      - exit_status: "*"
      
  - block: "this is block step"
  
  - command: echo "second command"
