steps:
  - block: "Request Release"
    fields: 
      - text: "Name"
        hint: "What’s the code name for this release? :name_badge:"
        key: "release-name"
      - select: "Stream"
        hint: "Which release stream does this belong in? :fork:"
        key: "release-stream"
        default: "beta"
        options:
          - label: "Beta"
            value: "beta"
          - label: "Stable"
            value: "stable"
  - command: release.sh
    label: ":rocket:"
